### ISSUE TITLE
Increase the amount of inotify watchers

### ISSUE THREAD

**Issue by taras** [this-dot/enterprise-ui-dev-box#3]
The following error shows up with current default setup.

```
Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1510310542: inotify-add-watch(/home/vagrant/s2bv4-ui-core/addons/payments-engine/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/test/lib) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

    at ChildProcess.<anonymous> (/home/vagrant/s2bv4-ui-core/addons/payments-engine/node_modules/fb-watchman/index.js:207:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

The problem can be resolved by increasing the number of inotify watchers. Here is more information https://github.com/facebook/watchman/issues/163#issuecomment-224263937

Running the following command after watchman install should fix the problem
```
echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_watches && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_queued_events && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_instances && watchman shutdown-server && sudo sysctl -p
```

**Comment by sivakumar-kailasam** [comment]
This already done as a part of 
https://github.com/this-dot/enterprise-ui-dev-box/blob/e9abbf19a5424e5de36e4666c1e5820555a377f9/scripts/common/watchman.sh#L11
